/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boolean_autotester_10 (
    input clk,
    input rst,
    input [0:0] button_next_test_case,
    input [0:0] button_speed_through,
    input button_reset,
    input [0:0] inv,
    output reg [4:0] current_test_case,
    output reg [1:0] current_statusPF,
    output reg [15:0] out
  );
  
  
  
  reg [4:0] M_current_test_case_register_d, M_current_test_case_register_q = 5'h00;
  
  reg [15:0] M_reg_current_out_d, M_reg_current_out_q = 1'h0;
  
  reg [0:0] M_speed_through_d, M_speed_through_q = 1'h0;
  
  
  localparam IDLE_state = 2'd0;
  localparam TESTING_state = 2'd1;
  localparam PASS_state = 2'd2;
  
  reg [1:0] M_state_d, M_state_q = IDLE_state;
  
  
  localparam NULL_track_failure = 1'd0;
  localparam FAIL_BEFORE_track_failure = 1'd1;
  
  reg M_track_failure_d, M_track_failure_q = NULL_track_failure;
  
  wire [16-1:0] M_aluUnit_out;
  wire [3-1:0] M_aluUnit_zvn;
  reg [16-1:0] M_aluUnit_a;
  reg [16-1:0] M_aluUnit_b;
  reg [1-1:0] M_aluUnit_inv;
  reg [6-1:0] M_aluUnit_alufn_signal;
  alu_7 aluUnit (
    .a(M_aluUnit_a),
    .b(M_aluUnit_b),
    .inv(M_aluUnit_inv),
    .alufn_signal(M_aluUnit_alufn_signal),
    .out(M_aluUnit_out),
    .zvn(M_aluUnit_zvn)
  );
  
  reg [1:0] sig_current_statusPF;
  
  always @* begin
    M_track_failure_d = M_track_failure_q;
    M_state_d = M_state_q;
    M_speed_through_d = M_speed_through_q;
    M_current_test_case_register_d = M_current_test_case_register_q;
    M_reg_current_out_d = M_reg_current_out_q;
    
    current_test_case = 5'h00;
    M_aluUnit_a = 16'h0000;
    M_aluUnit_b = 16'h0000;
    M_aluUnit_inv = inv;
    M_aluUnit_alufn_signal = 6'h00;
    M_state_d = IDLE_state;
    sig_current_statusPF = 2'h0;
    M_track_failure_d = NULL_track_failure;
    if (button_speed_through) begin
      M_speed_through_d = 1'h1;
    end
    
    case (M_state_q)
      IDLE_state: begin
        if (M_speed_through_q) begin
          M_state_d = TESTING_state;
          M_current_test_case_register_d = M_current_test_case_register_q + 5'h01;
        end
        if (button_next_test_case) begin
          M_state_d = TESTING_state;
          M_current_test_case_register_d = M_current_test_case_register_q + 5'h01;
        end
        if (button_reset) begin
          M_state_d = IDLE_state;
          M_current_test_case_register_d = 5'h00;
        end
      end
      TESTING_state: begin
        
        case (M_current_test_case_register_q)
          5'h01: begin
            M_aluUnit_a = 16'h00c1;
            M_aluUnit_b = 16'h00f6;
            M_aluUnit_alufn_signal = 6'h1a;
            current_test_case = M_current_test_case_register_q;
            sig_current_statusPF = 1'h1;
            if (M_aluUnit_out != 16'h00c1) begin
              M_track_failure_d = FAIL_BEFORE_track_failure;
              sig_current_statusPF = 2'h2;
            end
            M_state_d = IDLE_state;
          end
          5'h02: begin
            M_aluUnit_a = 16'h00c1;
            M_aluUnit_b = 16'h00f6;
            M_aluUnit_alufn_signal = 6'h1c;
            current_test_case = M_current_test_case_register_q;
            sig_current_statusPF = 1'h1;
            if (M_aluUnit_out != 16'h00f6) begin
              M_track_failure_d = FAIL_BEFORE_track_failure;
              sig_current_statusPF = 2'h2;
            end
            M_state_d = IDLE_state;
          end
          5'h03: begin
            M_aluUnit_a = 16'h00c1;
            M_aluUnit_b = 16'h00f6;
            M_aluUnit_alufn_signal = 6'h18;
            current_test_case = M_current_test_case_register_q;
            sig_current_statusPF = 1'h1;
            if (M_aluUnit_out != 16'h00c0) begin
              M_track_failure_d = FAIL_BEFORE_track_failure;
              sig_current_statusPF = 2'h2;
            end
            M_state_d = IDLE_state;
          end
          5'h04: begin
            M_aluUnit_a = 16'h00c1;
            M_aluUnit_b = 16'h00f6;
            M_aluUnit_alufn_signal = 6'h17;
            current_test_case = M_current_test_case_register_q;
            sig_current_statusPF = 1'h1;
            if (M_aluUnit_out != 16'h003f) begin
              M_track_failure_d = FAIL_BEFORE_track_failure;
              sig_current_statusPF = 2'h2;
            end
            M_state_d = IDLE_state;
          end
        endcase
      end
      5'h05: begin
        M_aluUnit_a = 16'h00c1;
        M_aluUnit_b = 16'h00f6;
        M_aluUnit_alufn_signal = 6'h1e;
        current_test_case = M_current_test_case_register_q;
        sig_current_statusPF = 1'h1;
        if (M_aluUnit_out != 16'h00f7) begin
          M_track_failure_d = FAIL_BEFORE_track_failure;
          sig_current_statusPF = 2'h2;
        end
        M_state_d = IDLE_state;
      end
      5'h06: begin
        M_aluUnit_a = 16'h00c1;
        M_aluUnit_b = 16'h00f6;
        M_aluUnit_alufn_signal = 6'h11;
        current_test_case = M_current_test_case_register_q;
        sig_current_statusPF = 1'h1;
        if (M_aluUnit_out != 16'h0008) begin
          M_track_failure_d = FAIL_BEFORE_track_failure;
          sig_current_statusPF = 2'h2;
        end
        M_state_d = IDLE_state;
      end
      5'h07: begin
        M_aluUnit_a = 16'h00c1;
        M_aluUnit_b = 16'h00f6;
        M_aluUnit_alufn_signal = 6'h16;
        current_test_case = M_current_test_case_register_q;
        sig_current_statusPF = 1'h1;
        if (M_aluUnit_out != 16'h0037) begin
          M_track_failure_d = FAIL_BEFORE_track_failure;
          sig_current_statusPF = 2'h2;
        end
        M_state_d = IDLE_state;
      end
      5'h08: begin
        M_aluUnit_a = 16'h00c1;
        M_aluUnit_b = 16'h00f6;
        M_aluUnit_alufn_signal = 6'h19;
        current_test_case = M_current_test_case_register_q;
        sig_current_statusPF = 1'h1;
        if (M_aluUnit_out != 16'h00c8) begin
          M_track_failure_d = FAIL_BEFORE_track_failure;
          sig_current_statusPF = 2'h2;
        end
        M_state_d = IDLE_state;
      end
      5'h09: begin
        M_state_d = PASS_state;
      end
      PASS_state: begin
        if (M_track_failure_q == FAIL_BEFORE_track_failure) begin
          sig_current_statusPF = 2'h2;
        end else begin
          sig_current_statusPF = 1'h1;
        end
        if (button_reset) begin
          M_state_d = IDLE_state;
        end
      end
    endcase
    M_reg_current_out_d = M_aluUnit_out;
    out = M_reg_current_out_q;
    current_test_case = M_current_test_case_register_q;
    current_statusPF = sig_current_statusPF;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_reg_current_out_q <= 1'h0;
    end else begin
      M_reg_current_out_q <= M_reg_current_out_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_speed_through_q <= 1'h0;
    end else begin
      M_speed_through_q <= M_speed_through_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_current_test_case_register_q <= 5'h00;
    end else begin
      M_current_test_case_register_q <= M_current_test_case_register_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_track_failure_q <= 1'h0;
    end else begin
      M_track_failure_q <= M_track_failure_d;
    end
  end
  
endmodule
