/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     NUM_CASES = 14
     SIZE = 5
     DIV = 27
*/
module custom_counter_25 (
    input clk,
    input rst,
    output reg [4:0] sel
  );
  
  localparam NUM_CASES = 4'he;
  localparam SIZE = 3'h5;
  localparam DIV = 5'h1b;
  
  
  wire [5-1:0] M_ctr_value;
  counter_30 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    sel = M_ctr_value;
  end
endmodule
